[package]
name = "garble"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
bytes = "1.1.0"
console-subscriber = { version = "0.1.3", optional = true }
crossterm = { version = "0.23.1", features = ["event-stream"] }
futures = "0.3.21"
pin-project = "1.0.10"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"]}
tokio-util = { version = "0.7.0", features = ["full"] }
clap = { version = "3.0", features = ["derive"] }
openssl = "0.10.38"
sha3 = "0.10.1"
tokio-stream = "0.1.8"
